<#
.SYNOPSIS
	Bundles every module under src/ into a single loadstring-ready file.

.DESCRIPTION
	Each src/<path>.lua becomes a lazily evaluated module keyed by its path
	(without extension, forward slashes). Modules load each other with
	import("core/Signal") etc. The entry module's return value is returned
	by the bundle.

.EXAMPLE
	./build.ps1                      # -> dist/Hellspawn.lua
	./build.ps1 -Append tests/x.luau # bundle + custom tail (for tooling)
#>
param(
	[string]$Out = "dist/Hellspawn.lua",
	[string]$Entry = "init",
	[string]$Append = ""
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$src = Join-Path $root "src"

$version = "dev"
$versionFile = Join-Path $root "VERSION"
if (Test-Path $versionFile) { $version = (Get-Content $versionFile -Raw).Trim() }

$files = Get-ChildItem -Path $src -Recurse -Filter *.lua | Sort-Object FullName
$sb = New-Object System.Text.StringBuilder

[void]$sb.AppendLine("--[[")
[void]$sb.AppendLine("    H E L L S P A W N   //   ImGui-styled interface library for Roblox")
[void]$sb.AppendLine("    version $version  -  bundled $(Get-Date -Format 'yyyy-MM-dd HH:mm')")
[void]$sb.AppendLine("    generated by build.ps1 from src/ - edit the sources, not this file")
[void]$sb.AppendLine("]]")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("local __VERSION = `"$version`"")
[void]$sb.AppendLine("local __modules = {}")
[void]$sb.AppendLine("local __cache = {}")
[void]$sb.AppendLine("local __loading = {}")
[void]$sb.AppendLine("local function __import(name)")
[void]$sb.AppendLine("	local cached = __cache[name]")
[void]$sb.AppendLine("	if cached ~= nil then")
[void]$sb.AppendLine("		return cached")
[void]$sb.AppendLine("	end")
[void]$sb.AppendLine("	local loader = __modules[name]")
[void]$sb.AppendLine("	if not loader then")
[void]$sb.AppendLine("		error(`"[Hellspawn] unknown module '`" .. tostring(name) .. `"'`", 2)")
[void]$sb.AppendLine("	end")
[void]$sb.AppendLine("	if __loading[name] then")
[void]$sb.AppendLine("		error(`"[Hellspawn] circular import of '`" .. name .. `"'`", 2)")
[void]$sb.AppendLine("	end")
[void]$sb.AppendLine("	__loading[name] = true")
[void]$sb.AppendLine("	local result = loader(__import, __VERSION)")
[void]$sb.AppendLine("	__loading[name] = nil")
[void]$sb.AppendLine("	if result == nil then")
[void]$sb.AppendLine("		result = true")
[void]$sb.AppendLine("	end")
[void]$sb.AppendLine("	__cache[name] = result")
[void]$sb.AppendLine("	return result")
[void]$sb.AppendLine("end")
[void]$sb.AppendLine("")

foreach ($file in $files) {
	$rel = $file.FullName.Substring($src.Length + 1).Replace("\", "/")
	$name = $rel.Substring(0, $rel.Length - 4)
	$body = [System.IO.File]::ReadAllText($file.FullName)
	[void]$sb.AppendLine("-- >>> $rel")
	[void]$sb.AppendLine("__modules[`"$name`"] = function(import, VERSION)")
	[void]$sb.AppendLine($body.TrimEnd())
	[void]$sb.AppendLine("end")
	[void]$sb.AppendLine("")
}

if ($Append -ne "") {
	$tail = [System.IO.File]::ReadAllText((Resolve-Path $Append))
	[void]$sb.AppendLine("-- >>> appended: $Append")
	[void]$sb.AppendLine($tail)
} else {
	[void]$sb.AppendLine("return __import(`"$Entry`")")
}

$outPath = if ([System.IO.Path]::IsPathRooted($Out)) { $Out } else { Join-Path $root $Out }
$outDir = Split-Path -Parent $outPath
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Force $outDir | Out-Null }
$utf8 = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outPath, $sb.ToString().Replace("`r`n", "`n"), $utf8)

$lines = ($sb.ToString() -split "`n").Count
Write-Host ("bundled {0} modules -> {1} ({2:N0} lines, {3:N0} KB)" -f $files.Count, $outPath, $lines, ((Get-Item $outPath).Length / 1KB))
